added sample template and digesting DB info
RedHatInsights/cookiecutter-backend-starter-app-python pull request #12
Opened 2023-08-21 17:50 UTC by mjholder

Ticket: RHCLOUD-27780
Adding a sample cdappconfig.json
Digesting DB info for when we eventually add postgres support

2023-08-22 15:03 UTC, Victoremepunto requested changes
There's a few items remaining here - this is changing the DB to be set as PostgreSQL, I believe we need something to spin up a PostgreSQL service now (I don't know but I believe the application won't start if there's not a db connection) .

I think we need to add a new recipe in the Makefile to spin up a postgreSQL container (either using docker/podman commands or using a compose file)

And the GH actions need to spin up a PostgreSQL service for the tests to run - or - we could switch to use a SQLite db for unit tests, and have an actual container running only on the E2E tests - what do you think ?

2023-08-22 15:03 UTC, Victoremepunto commented on {{cookiecutter.project_name}}/src/{{cookiecutter.project_name}}/settings.py
>  if isClowderEnabled():
I think what we wanted to do with the CDAPPCONFIG wrapper is not to do an IF condition on whether if Clowder is enabled or not (maybe change it to raise an exception if not enabled) - we wanted to try and force config on CDAPPCONFIG.

2023-08-23 12:00 UTC, mjholder commented on {{cookiecutter.project_name}}/src/{{cookiecutter.project_name}}/settings.py
>  if isClowderEnabled():
Ok I added an exception that will be thrown if the app is not clowder enabled.

2023-08-29 13:17 UTC, Victoremepunto approved these changes
LGTM - small suggestions - feel free to disregard, we can tackle them in a followup

2023-08-29 13:17 UTC, Victoremepunto commented on {{cookiecutter.project_name}}/src/{{cookiecutter.project_name}}/settings.py
> +import sys
is this needed ? if not - why is this not caught by our automatic linter ?

2023-08-29 13:17 UTC, Victoremepunto commented on {{cookiecutter.project_name}}/Makefile
> +	ACG_CONFIG=cdappconfig.json coverage run --source="." manage.py test
no need since exporting `ACG_CONFIG` at the top.
```suggestion
	coverage run --source="." manage.py test
```

2023-08-29 13:17 UTC, Victoremepunto commented on {{cookiecutter.project_name}}/Makefile
> +NAMESPACE=''
Should not be set, but only defined externally.

An alternative would be to refactor the `namespace_check` recipe to look for not empty, instead of `if ndef` as this will always evaluate to true when given a default value.

2023-08-29 13:17 UTC, Victoremepunto commented on {{cookiecutter.project_name}}/README.md
> +```
This description is fine, providing context of what needs to happen - a db service needs to be up and listening - , however we already take care of this using the `make run` recipe, having the `start-db` as a requirement, so there's no need to run `start-db` manually.

2023-08-29 13:17 UTC, Victoremepunto commented on {{cookiecutter.project_name}}/pyproject.toml
> +    "psycopg",
Only FYI since I made this change , I read the recommendation is to use this instead of `psycopg2` as [the latter will be deprecated](https://docs.djangoproject.com/en/4.2/ref/databases/#postgresql-notes)

2023-08-29 13:25 UTC, mjholder commented on {{cookiecutter.project_name}}/src/{{cookiecutter.project_name}}/settings.py
> +import sys
yeah that's weird the linter didn't notice this. I removed it

2023-08-29 13:43 UTC, merged