probes moved to middleware and improved
RedHatInsights/cookiecutter-backend-starter-app-python pull request #5
Opened 2023-07-25 12:39 UTC by mjholder

The probes now exist in a middleware. I have this because requests go through middlewares before views. If something is wrong and we have our probes in the view, the error will propagate before we can check anything ourselves. With the probes being in a middleware, we can run our tests and return results first.

liveness (/livez): we check if we have a valid connection to the db and make sure the cache isn't failing.
readiness (/readyz): we check if there are migrations that need to be run (room for improvement)

2023-08-16 21:02 UTC, Victoremepunto requested changes
Please, can you ...
- Remove the healthz endpoint 
- Add `livenessProbe` and `readinessProbe` definitions in the Clowdapp template to use the two corresponding endpoints (`livez/` and `/readyz`) ? 

Today the Clowdapp defaults to use `/healthz` which is a dummy implementation in our Starter App anyways.

2023-08-17 11:31 UTC, mjholder commented
> Please, can you ...
> 
>     * Remove the healthz endpoint
> 
>     * Add `livenessProbe` and `readinessProbe` definitions in the Clowdapp template to use the two corresponding endpoints (`/livez` and `/readyz`) ?
> 
> 
> Today the Clowdapp defaults to use `/healthz` which is a dummy implementation in our Starter App anyways.

Ok I made those changes. Is there a way to test them?

2023-08-21 10:25 UTC, Victoremepunto commented
> Ok I made those changes. Is there a way to test them?

Yes, but only on a deployment to a K8s cluster. I think we should add a pr_check Jenkinsfile for this. Gonna create a card. 

You can do this "manually" by running  `make build-image  push-image deploy`

2023-08-21 10:36 UTC, Victoremepunto requested changes
Almost there, a couple of syntax issues I've spotted on the template.

2023-08-21 10:36 UTC, Victoremepunto commented on {{cookiecutter.project_name}}/clowdapp.yaml
> +  value: 8000
Needs quotes

```suggestion
  value: "8000"
```

2023-08-21 10:36 UTC, Victoremepunto commented on {{cookiecutter.project_name}}/clowdapp.yaml
> +            port: ${WEB_PORT}
Use the `${{VALUE}}` syntax for setting as a JSON value (not a String).

See https://docs.openshift.com/container-platform/4.13/openshift_images/using-templates.html#templates-writing-parameters_using-templates

```suggestion
            port: ${{WEB_PORT}}
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /readyz
            port: ${{WEB_PORT}}
```

2023-08-21 15:26 UTC, Victoremepunto approved these changes

2023-08-21 15:42 UTC, merged